name: patient_app
description: Flutter App to manage patients data

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  lottie: ^1.0.1
  #chart
  cupertino_icons: ^1.0.2
  flutter_icons: ^1.1.0
  page_transition: ^1.1.7+6
  animated_bottom_navigation_bar: ^0.2.1
  fl_chart: ^0.36.2
  percent_indicator: "^2.1.7+2"
  # firebase
  cloud_firestore: ^2.2.1
  firebase_core: ^1.2.1
  firebase_auth: ^1.2.0
  qr_flutter: ^3.2.0
  qrscan: ^0.2.22
  easy_gradient_text: ^1.0.0
  responsive_widgets: ^0.1.10
  auto_animated: ^1.2.3
  flutter_staggered_animations: ^0.1.2
  cached_network_image: ^2.0.0-rc
  provider: ^5.0.0
  google_sign_in: ^4.5.9
  flutter_signin_button: ^1.0.0
  firebase: ^9.0.1
  flare_flutter: ^3.0.0
  flutter_bloc: ^7.0.0
  shared_preferences: ^2.0.6
  charts_flutter: ^0.10.0
  intl: ^0.17.0
  flutter_local_notifications: ^5.0.0+1
  auto_size_text: ^2.1.0
  firebase_database: ^6.0.0
  fluttertoast: ^8.0.7
  google_fonts: ^2.1.0
  image_picker: ^0.8.0+1
  path: ^1.8.0
  flutter_svg: ^0.22.0
  file_picker: ^3.0.2+2
  rflutter_alert: ^2.0.2
  firebase_storage: ^8.1.1



flutter_native_splash:
  image: assets/blue.png
  color: "42a5f5"
  fill: true


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/category/
    - assets/onBoardDoc.png
    - assets/images/docprofile/
    - assets/images/docinfo/
    - assets/animations/Success Check.flr
    - assets/animations/
    - assets/sound/

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  fonts:
    - family: avenir
      fonts:
        - asset: assets/font/avenir.ttf
    - family: Ic
      fonts:
        - asset: assets/fonts/ic/ic_medicine.ttf
    - family: Angel
      fonts:
        - asset: assets/fonts/neu/Angel Signature.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
